name: minifyJS
on: 
  push:
    branches: [master]
jobs:
  minify:
    runs-on: ubuntu-latest
    environment: masterAutoPush
    if: github.ref == 'refs/heads/master'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        #  token: ${{ secrets.PAT }}
    
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
    
      # Auto commits minified content to the existing files
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
          push_options: --force
